In [1]:
import pandas as pd
import numpy as np

In [2]:
a=np.array([-1,1])

b=np.array([1,1])

np.dot(a,b)

np.int64(0)

In [3]:
X=np.array([[1,0,1],[2,2,2]])

out=X[0:2,2]

In [4]:
out

array([1, 2])

In [5]:
X

array([[1, 0, 1],
       [2, 2, 2]])

In [7]:
X=np.array([[1,0],[0,1]])

Y=np.array([[2,2],[2,2]])

Z=np.dot(X,Y)

In [8]:
Z

array([[2, 2],
       [2, 2]])

In [10]:
x = "Gone"

if x == "Go":

    print('Go')

else:

    print('Stop')

print('Mike')

Stop
Mike
